{{- if .Values.datadog.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eksdemo.fullname" . }}-datadog
type: Opaque
stringData:
  api-key: {{ required "A valid .Values.datadog.apiKey is required when createSecret is true" .Values.datadog.apiKey | quote }}
{{- end }}
